In [1]:
import os
import pandas as pd
import re
import itertools
import json
import numpy as np

from utilities.loaders import load_results, summarize_results
from argparse import ArgumentParser

In [2]:
# load results.json 
hossain_lr_results = load_results("hossain_lr_results.json")
hossain_lr_results_sum = summarize_results(estimator_name="lr", results=hossain_lr_results)

In [3]:
hossain_lr_results

{'lr': {'C_0.01': {'folds_train_acc': [0.9277864830316276,
    0.9271908348054255,
    0.9240318236696282,
    0.9236406424177367,
    0.9250875218159099,
    0.9246532318686863,
    0.923558742324968,
    0.9278819849487452,
    0.9244443528951326,
    0.9330731365724054,
    0.9238575026988125,
    0.9250779362883745,
    0.9282095204680776,
    0.9241977111245926,
    0.9239472871409451,
    0.9254604817347378,
    0.9252525252525252,
    0.9249031407138736,
    0.923947786278432,
    0.9247129275219163,
    0.9242955567473906,
    0.9246341312804891,
    0.9249382716049382,
    0.93293497509398,
    0.9273572076155938,
    0.9258395185349588,
    0.9235081561015899,
    0.925595114883047,
    0.923443295347708,
    0.9257503293875984,
    0.9262268977491036,
    0.9289111260122763,
    0.9238828552478859],
   'folds_cross_acc': [0.8501335113484646,
    0.8805876836511409,
    0.9750889679715302,
    0.9884467265725289,
    0.9456899273760657,
    0.9612322602976808,
    0.9969304229195088,
    0.8559565633982753,
    0.9697178251892636,
    0.6651693158258466,
    0.9963436928702011,
    0.946896992962252,
    0.8441642418364048,
    0.9741536221332363,
    0.9885017421602788,
    0.9308224442736357,
    0.9389261744966443,
    0.9522357723577236,
    0.9810882548108826,
    0.9580369843527738,
    0.9609067017082786,
    0.9611856033874383,
    0.9492857142857143,
    0.7227233052080303,
    0.8630790190735694,
    0.9248961329498242,
    0.9942675159235669,
    0.9384615384615385,
    0.9931442817076971,
    0.9307287337212524,
    0.905674558436678,
    0.8159869494290375,
    0.9771689497716894],
   'folds_train_prec': [0.8126195028680688,
    0.8108949416342413,
    0.8129646840148699,
    0.8115806677562456,
    0.8126032570214775,
    0.814002828854314,
    0.8123980424143556,
    0.8138677157610031,
    0.8136819985991127,
    0.8188194038573934,
    0.8121226196005573,
    0.8131147540983606,
    0.8121963070942663,
    0.8107226107226108,
    0.8125437164840289,
    0.8135352579271179,
    0.812411179535765,
    0.8131348925112214,
    0.8121197941038839,
    0.8120300751879699,
    0.808660861379148,
    0.8112459169388707,
    0.8120283018867924,
    0.8114977307110439,
    0.8135245901639344,
    0.8129408902943323,
    0.8128504672897197,
    0.8137461881304245,
    0.8132332238385734,
    0.8153661464585834,
    0.8137847642079806,
    0.8060010346611485,
    0.8130841121495327],
   'folds_cross_prec': [0.86,
    0.8093126385809313,
    0.22448979591836735,
    0.6666666666666666,
    0.7924528301886793,
    0.7407407407407407,
    0.0,
    0.8258426966292135,
    0.2727272727272727,
    0.9237918215613383,
    0.6666666666666666,
    1.0,
    0.875968992248062,
    0.48148148148148145,
    1.0,
    0.5740740740740741,
    0.9047619047619048,
    0.6857142857142857,
    0.6470588235294118,
    1.0,
    0.7608695652173914,
    0.8571428571428571,
    1.0,
    0.8487584650112867,
    0.779291553133515,
    0.8031914893617021,
    0.5555555555555556,
    0.8863636363636364,
    1.0,
    0.6636363636363637,
    0.8910891089108911,
    0.9411764705882353,
    0.5333333333333333],
   'folds_train_rec': [0.3533936181270138,
    0.3309687665431445,
    0.34795147175815433,
    0.34528657991457234,
    0.3476724224982329,
    0.34595731890592124,
    0.34511434511434513,
    0.346996540517874,
    0.34770028933453057,
    0.32277387397765234,
    0.34644343174162867,
    0.3495771244462344,
    0.35089744935446626,
    0.3464833632197649,
    0.3461462058005562,
    0.3469223007063572,
    0.3468149646107179,
    0.34631250628835897,
    0.3455794504181601,
    0.3465356462448611,
    0.34487604135300615,
    0.3480132118907016,
    0.3463085898209616,
    0.31423550087873464,
    0.33435098431413834,
    0.3425233165932151,
    0.34489937543372656,
    0.3516828872668289,
    0.34384920634920635,
    0.34709730171708914,
    0.3442103109656301,
    0.33661013287242086,
    0.34713216957605986],
   'folds_cross_rec': [0.088659793814433,
    0.5521936459909228,
    0.22,
    0.15384615384615385,
    0.20689655172413793,
    0.16,
    0.0,
    0.25925925925925924,
    0.03614457831325301,
    0.3487719298245614,
    0.3333333333333333,
    0.04597701149425287,
    0.19516407599309155,
    0.5735294117647058,
    0.13157894736842105,
    0.3163265306122449,
    0.17592592592592593,
    0.2874251497005988,
    0.1774193548387097,
    0.11278195488721804,
    0.24475524475524477,
    0.05217391304347826,
    0.13414634146341464,
    0.47867600254614895,
    0.471169686985173,
    0.4326647564469914,
    0.2631578947368421,
    0.16115702479338842,
    0.15384615384615385,
    0.453416149068323,
    0.2727272727272727,
    0.3580683156654888,
    0.09876543209876543],
   'folds_train_f1': [0.4925751539297356,
    0.4700751879699248,
    0.4873259052924791,
    0.48445993031358886,
    0.48698727015558696,
    0.48555157139843913,
    0.48443579766536965,
    0.48655005144789065,
    0.4872081644065427,
    0.4630256961084029,
    0.48569444444444443,
    0.4889452189832418,
    0.49006816682547827,
    0.48548297040759353,
    0.48547746743748693,
    0.4864176570458404,
    0.4861111111111111,
    0.4857465424781259,
    0.48484425199050146,
    0.4857685009487666,
    0.48353504081058263,
    0.4870771170413952,
    0.4855450571146524,
    0.45304054054054055,
    0.47392374841453405,
    0.48197288722238246,
    0.48430430848472195,
    0.49111630211651447,
    0.48333565750941293,
    0.48691662484765935,
    0.4837898066278485,
    0.4748914120246895,
    0.48654316672492137],
   'folds_cross_f1': [0.16074766355140188,
    0.6564748201438849,
    0.2222222222222222,
    0.25,
    0.328125,
    0.2631578947368421,
    0.0,
    0.3946308724832215,
    0.06382978723404255,
    0.5063678043810494,
    0.4444444444444444,
    0.08791208791208792,
    0.3192090395480226,
    0.5234899328859061,
    0.23255813953488372,
    0.40789473684210525,
    0.29457364341085274,
    0.4050632911392405,
    0.27848101265822783,
    0.20270270270270271,
    0.37037037037037035,
    0.09836065573770492,
    0.23655913978494625,
    0.6121286121286121,
    0.5872689938398358,
    0.5623836126629422,
    0.35714285714285715,
    0.2727272727272727,
    0.26666666666666666,
    0.5387453874538746,
    0.4176334106728538,
    0.5187713310580204,
    0.16666666666666666],
   'folds_train_roc_auc': [0.6722108106427616,
    0.6613118021094311,
    0.6693414687841007,
    0.6679955827110096,
    0.6692693183467813,
    0.668450942248783,
    0.6679289802543451,
    0.6691641353682922,
    0.6692676774853105,
    0.6578811411166181,
    0.6685814111823285,
    0.6701992958156272,
    0.6710255157049283,
    0.668586519080501,
    0.6684557038053802,
    0.6689576755909256,
    0.6688625494464125,
    0.6686159645402464,
    0.668171703999538,
    0.6686814560984095,
    0.6677652309118093,
    0.6693665141759214,
    0.6685873784099879,
    0.6535791036451654,
    0.6630185801488468,
    0.666847901609967,
    0.6678341967231209,
    0.6712653912566336,
    0.6673346434232451,
    0.6691090559066353,
    0.667708321203496,
    0.6640280528181991,
    0.6689402564756478],
   'folds_cross_roc_auc': [0.5429360299219516,
    0.7591543486061785,
    0.6037520552449852,
    0.5764355891102722,
    0.6015926753222579,
    0.5787337192474674,
    0.4993167065254527,
    0.6235843878199573,
    0.5166553568151457,
    0.6604308934350854,
    0.6662994246541805,
    0.5229885057471264,
    0.5943998582033874,
    0.778925960081681,
    0.5657894736842105,
    0.6486038305596553,
    0.5872393739615158,
    0.63976284415012,
    0.5876934172567532,
    0.556390977443609,
    0.6204817244114038,
    0.5259030653852919,
    0.5670731707317074,
    0.7034323206728601,
    0.7181954059657509,
    0.7096777019645029,
    0.6309381271185011,
    0.5797818266095687,
    0.5769230769230769,
    0.7154516096725856,
    0.6340041340041339,
    0.674747154222636,
    0.5483602211618571]},
  'C_0.1': {'folds_train_acc': [0.9280545132159499,
    0.9274904184874123,
    0.9241659701369326,
    0.9238470748524008,
    0.9253870064957195,
    0.9248282892772188,
    0.9237132731693246,
    0.9281607118892525,
    0.924722433930006,
    0.93347475954112,
    0.9240836888911736,
    0.9252843900324133,
    0.928343669703943,
    0.9247632463780038,
    0.9242458560691856,
    0.9256555576089858,
    0.9255411255411256,
    0.9251092243013767,
    0.924298352339513,
    0.9248981355722928,
    0.9245430917117042,
    0.9248296729308606,
    0.9251748971193415,
    0.9329556869608442,
    0.9274808373856425,
    0.9260563016795532,
    0.923797233119967,
    0.925657213827365,
    0.9238255622940149,
    0.9259474432260273,
    0.9264631853624961,
    0.929065868881209,
    0.9241730227159675],
   'folds_cross_acc': [0.8514686248331108,
    0.8787120975304783,
    0.9767065674538984,
    0.9884467265725289,
    0.9456899273760657,
    0.9619245413637937,
    0.9969304229195088,
    0.8549984030661131,
    0.9700619408121128,
    0.6668970283344852,
    0.9963436928702011,
    0.9472168905950096,
    0.8448108632395732,
    0.9745176556243175,
    0.9885017421602788,
    0.930053804765565,
    0.938255033557047,
    0.9525745257452575,
    0.9814200398142005,
    0.9580369843527738,
    0.9592641261498029,
    0.9615384615384616,
    0.9492857142857143,
    0.7195228396857725,
    0.8623978201634878,
    0.925215723873442,
    0.9942675159235669,
    0.9369822485207101,
    0.9931442817076971,
    0.9315599889165974,
    0.9075535512965051,
    0.8169657422512235,
    0.9774543378995434],
   'folds_train_prec': [0.8105312646920545,
    0.8095967330270546,
    0.8081038015023901,
    0.8098640239686564,
    0.8121212121212121,
    0.811961833837561,
    0.8098850574712644,
    0.8121974830590513,
    0.8125287885766928,
    0.818651362984218,
    0.8103527256069629,
    0.81209453197405,
    0.8071343638525564,
    0.8115411037325395,
    0.8125,
    0.8102766798418972,
    0.8114485981308411,
    0.812105632157046,
    0.8114338404794836,
    0.8097775718257646,
    0.8070053351890513,
    0.8086377211118768,
    0.8101324657215896,
    0.804251550044287,
    0.8090452261306532,
    0.8122291766971593,
    0.8111775528978841,
    0.8097989369077883,
    0.8130927596576452,
    0.8111476952022577,
    0.8122614503816794,
    0.803312101910828,
    0.81313598519889],
   'folds_cross_prec': [0.8571428571428571,
    0.7948164146868251,
    0.25,
    0.6666666666666666,
    0.7924528301886793,
    0.7586206896551724,
    0.0,
    0.8228571428571428,
    0.35714285714285715,
    0.9213893967093236,
    0.6666666666666666,
    1.0,
    0.8721804511278195,
    0.4878048780487805,
    1.0,
    0.5625,
    0.8636363636363636,
    0.6901408450704225,
    0.625,
    1.0,
    0.6507936507936508,
    1.0,
    1.0,
    0.8429378531073446,
    0.776566757493188,
    0.8074866310160428,
    0.5555555555555556,
    0.7959183673469388,
    1.0,
    0.6637554585152838,
    0.8888888888888888,
    0.941717791411043,
    0.5625],
   'folds_train_rec': [0.3583827045005717,
    0.3358390682901006,
    0.35302307080350037,
    0.34906128936127945,
    0.3518125820458447,
    0.34956417192666067,
    0.3487773487773488,
    0.35181884893594717,
    0.35199042202933256,
    0.32864877318281305,
    0.3505052506439469,
    0.35289971808296416,
    0.3562506560302299,
    0.3530583781629807,
    0.3499205403257847,
    0.35166498486377396,
    0.3511627906976744,
    0.3496327598349935,
    0.350457984866587,
    0.35044620475283267,
    0.3491920104386229,
    0.35231708537683915,
    0.35063367531683765,
    0.31915641476274165,
    0.3389830508474576,
    0.34580301322127704,
    0.3496579756121741,
    0.35523114355231145,
    0.34871031746031744,
    0.35251430907604253,
    0.34830196399345337,
    0.3406071081343848,
    0.3507231920199501],
   'folds_cross_rec': [0.09896907216494845,
    0.556732223903177,
    0.22,
    0.15384615384615385,
    0.20689655172413793,
    0.176,
    0.0,
    0.25396825396825395,
    0.060240963855421686,
    0.35368421052631577,
    0.3333333333333333,
    0.05172413793103448,
    0.2003454231433506,
    0.5882352941176471,
    0.13157894736842105,
    0.32142857142857145,
    0.17592592592592593,
    0.2934131736526946,
    0.24193548387096775,
    0.11278195488721804,
    0.2867132867132867,
    0.05217391304347826,
    0.13414634146341464,
    0.4748567791215786,
    0.4695222405271829,
    0.4326647564469914,
    0.2631578947368421,
    0.16115702479338842,
    0.15384615384615385,
    0.4720496894409938,
    0.2909090909090909,
    0.36160188457008247,
    0.1111111111111111],
   'folds_train_f1': [0.497009009009009,
    0.4747436952780064,
    0.49138348674648763,
    0.4878522837706511,
    0.49094624110477,
    0.48872391091189243,
    0.48757871427582866,
    0.4909662789847122,
    0.49119387399930386,
    0.46901200065757026,
    0.48934993084370676,
    0.49199887703537337,
    0.49431983687736675,
    0.49205137105171814,
    0.4891696750902527,
    0.4904651326437267,
    0.4901905434015526,
    0.4888169925446617,
    0.4895007648449451,
    0.48918748687801805,
    0.4874597169679137,
    0.49079754601226994,
    0.48943488943488944,
    0.45697030699547053,
    0.47778025076044217,
    0.4850837466752929,
    0.4886733633529616,
    0.493834120217039,
    0.4880927584531001,
    0.4914505557138786,
    0.48754295532646047,
    0.47837960855712336,
    0.49006899435500734],
   'folds_cross_f1': [0.17744916820702403,
    0.6548042704626335,
    0.23404255319148937,
    0.25,
    0.328125,
    0.2857142857142857,
    0.0,
    0.3881401617250674,
    0.10309278350515463,
    0.5111561866125761,
    0.4444444444444444,
    0.09836065573770492,
    0.3258426966292135,
    0.5333333333333333,
    0.23255813953488372,
    0.4090909090909091,
    0.2923076923076923,
    0.4117647058823529,
    0.3488372093023256,
    0.20270270270270271,
    0.39805825242718446,
    0.09917355371900827,
    0.23655913978494625,
    0.6074918566775245,
    0.5852156057494866,
    0.5634328358208955,
    0.35714285714285715,
    0.26804123711340205,
    0.26666666666666666,
    0.5517241379310345,
    0.4383561643835616,
    0.5225531914893617,
    0.18556701030927836],
   'folds_train_roc_auc': [0.674579471220795,
    0.6636496499928456,
    0.6716585078724766,
    0.6697792711017324,
    0.6712703770691665,
    0.6701453362789507,
    0.6696339973272604,
    0.6714665067993602,
    0.6713208647914691,
    0.6607507366055428,
    0.6705033394356121,
    0.671785830148657,
    0.6734846779807822,
    0.6718109640055288,
    0.6702911837646933,
    0.671168995723767,
    0.6709503842160471,
    0.6702014721582527,
    0.6705247068175957,
    0.6705163432180147,
    0.6698140112657749,
    0.671380796775027,
    0.6706353184853918,
    0.6558123601509441,
    0.6651518920085515,
    0.6684246142626807,
    0.6700982535915272,
    0.6728723839851096,
    0.6696960036056647,
    0.6716212706025426,
    0.6696570747527995,
    0.6659010813830527,
    0.670689509414469],
   'folds_cross_roc_auc': [0.5478915452421715,
    0.7596505879169156,
    0.6045741532390662,
    0.5764355891102722,
    0.6015926753222579,
    0.5867337192474674,
    0.4993167065254527,
    0.6209388851744546,
    0.5285264330435452,
    0.662206298591953,
    0.6662994246541805,
    0.5258620689655172,
    0.5967916455414446,
    0.7862789012581517,
    0.5657894736842105,
    0.6505314095713098,
    0.5868775794607923,
    0.6427568561261677,
    0.6194433516915814,
    0.556390977443609,
    0.6395648474242063,
    0.5260869565217391,
    0.5670731707317074,
    0.7001829447590744,
    0.7171569983228443,
    0.7098575580796108,
    0.6309381271185011,
    0.5789851408224431,
    0.5769230769230769,
    0.7243120366888571,
    0.642880542880543,
    0.6765139386749328,
    0.55453306066803]},
  'C_1': {'folds_train_acc': [0.9279308069770319,
    0.9276866974514726,
    0.924351711399354,
    0.9240018991783989,
    0.9253870064957195,
    0.9250445366642296,
    0.9239193142951333,
    0.9280161868089895,
    0.9247430325251818,
    0.9336395279385414,
    0.9241145324628592,
    0.9252430992836055,
    0.9284262230798601,
    0.9246707042456274,
    0.9243179244311747,
    0.9259533049959958,
    0.9255823541537828,
    0.9252431786332537,
    0.924246798507001,
    0.9249701609252171,
    0.9247493708486324,
    0.9249943395838051,
    0.9253086419753086,
    0.9329453310274122,
    0.9277693068490893,
    0.9261079167139804,
    0.9239211232707,
    0.9257710618919478,
    0.923773904598568,
    0.9259370688134785,
    0.9264220918645147,
    0.9291071336462579,
    0.9241937489636877],
   'folds_cross_acc': [0.8521361815754339,
    0.8780869021569241,
    0.9773536072468457,
    0.9878048780487805,
    0.9456899273760657,
    0.9622706818968502,
    0.9969304229195088,
    0.8527626956244011,
    0.9700619408121128,
    0.6665514858327575,
    0.9963436928702011,
    0.9472168905950096,
    0.8451341739411574,
    0.9745176556243175,
    0.9885017421602788,
    0.931206764027671,
    0.9389261744966443,
    0.9525745257452575,
    0.9810882548108826,
    0.9580369843527738,
    0.959592641261498,
    0.9615384615384616,
    0.9492857142857143,
    0.7209775967413442,
    0.8634196185286104,
    0.9268136784915308,
    0.9942675159235669,
    0.9381656804733728,
    0.9931442817076971,
    0.9318370739817123,
    0.9071777527245396,
    0.8169657422512235,
    0.9774543378995434],
   'folds_train_prec': [0.8088304368248004,
    0.8098859315589354,
    0.8098703661587446,
    0.8092406221408966,
    0.8096669750231268,
    0.8104319852941176,
    0.8117539026629935,
    0.8084134615384615,
    0.8110398534127348,
    0.8196627607887969,
    0.8097739209865266,
    0.8093376264949402,
    0.8075005934013767,
    0.8077621425329097,
    0.8106563000228676,
    0.8124131542380731,
    0.810320781032078,
    0.8112244897959183,
    0.8090763236305295,
    0.8083735909822867,
    0.8069044879171462,
    0.8090555682597759,
    0.8094139363174896,
    0.8015222482435597,
    0.8092988562904028,
    0.8115559817789499,
    0.8118402937127123,
    0.8098526703499079,
    0.810004589261129,
    0.8111032698188662,
    0.8095689246802463,
    0.8021281986318723,
    0.8099268069533394],
   'folds_cross_prec': [0.828125,
    0.7978021978021979,
    0.2619047619047619,
    0.5454545454545454,
    0.7924528301886793,
    0.7666666666666667,
    0.0,
    0.8192771084337349,
    0.35714285714285715,
    0.9227941176470589,
    0.6666666666666666,
    1.0,
    0.8731343283582089,
    0.4878048780487805,
    1.0,
    0.5765765765765766,
    0.8695652173913043,
    0.6901408450704225,
    0.6,
    1.0,
    0.6666666666666666,
    1.0,
    1.0,
    0.8430493273542601,
    0.7754010695187166,
    0.8125,
    0.5555555555555556,
    0.8367346938775511,
    1.0,
    0.6696428571428571,
    0.8807339449541285,
    0.941717791411043,
    0.5625],
   'folds_train_rec': [0.3579669473027752,
    0.33827421916357864,
    0.35411694510739855,
    0.35144531638025234,
    0.3535292335655862,
    0.35337140567077446,
    0.35006435006435005,
    0.35255267847782784,
    0.35328743889055175,
    0.33037668471374265,
    0.3512978006736675,
    0.35430930326218285,
    0.3570903747244673,
    0.35455269974098425,
    0.3521056813667064,
    0.3539858728557013,
    0.3524772497472194,
    0.35194687594325386,
    0.3514536041417762,
    0.3523513486413316,
    0.35190203753889393,
    0.35411870683615254,
    0.3528465097565882,
    0.320796719390744,
    0.3426676492262343,
    0.3469304089371733,
    0.3507484881530683,
    0.3566504460665045,
    0.3501984126984127,
    0.35241210139002455,
    0.3496317512274959,
    0.34201145079399375,
    0.35321695760598504],
   'folds_cross_rec': [0.10927835051546392,
    0.5491679273827534,
    0.22,
    0.15384615384615385,
    0.20689655172413793,
    0.184,
    0.0,

In [4]:
hossain_lr_results_sum

                       C_0.01     C_0.1       C_1
folds_train_acc      0.925704  0.925941  0.926015
folds_cross_acc      0.925383  0.925416  0.925571
folds_train_prec     0.812586  0.810586  0.809619
folds_cross_prec     0.741581  0.741671  0.739394
folds_train_rec      0.343979  0.348386  0.350021
folds_cross_rec      0.240908  0.248332  0.249325
folds_train_f1       0.483295  0.487274  0.488697
folds_cross_f1       0.334767  0.342780  0.344215
folds_train_roc_auc  0.667526  0.669614  0.670380
folds_cross_roc_auc  0.615626  0.619088  0.619614

# best hossain lr results come from a hyper param config of C_10

In [5]:
# load results.json 
hossain_gbt_results = load_results("hossain_gbt_results.json")
hossain_gbt_results_sum = summarize_results(estimator_name="gbt", results=hossain_gbt_results)

FileNotFoundError: File not found please run `tuning.py` first to obtain `.json` file of results!

In [6]:
hossain_gbt_results_sum

,n_estimators_200|learning_rate_0.01|max_depth_3,n_estimators_200|learning_rate_0.01|max_depth_5,n_estimators_200|learning_rate_0.01|max_depth_10,n_estimators_200|learning_rate_0.1|max_depth_3,n_estimators_200|learning_rate_0.1|max_depth_5,n_estimators_200|learning_rate_0.1|max_depth_10,n_estimators_400|learning_rate_0.01|max_depth_3,n_estimators_400|learning_rate_0.01|max_depth_5
mean_train_acc,0.925041,0.929946,0.948694,0.933874,0.939918,0.971337,0.930252,0.934115
mean_cross_acc,0.923915,0.923478,0.922935,0.924987,0.924393,0.920569,0.924926,0.924655
mean_train_prec,0.789136,0.805470,0.924501,0.777757,0.810710,0.978247,0.782111,0.789524
mean_cross_prec,0.762314,0.723141,0.710339,0.684369,0.665413,0.557264,0.709195,0.691418
mean_train_rec,0.361388,0.412491,0.537109,0.485419,0.530289,0.733280,0.431017,0.476008
mean_cross_rec,0.245141,0.265559,0.278777,0.312366,0.321047,0.324807,0.281518,0.299588
mean_train_f1,0.495703,0.545543,0.679426,0.597722,0.641148,0.838220,0.555714,0.593889
mean_cross_f1,0.338489,0.361211,0.372977,0.398501,0.402569,0.385273,0.375729,0.389482
mean_train_roc_auc,0.675208,0.700585,0.766076,0.734892,0.758164,0.865718,0.708742,0.730851
mean_cross_roc_auc,0.616356,0.626510,0.632543,0.648361,0.651873,0.651305,0.634050,0.642361

In [6]:
# load results.json 
cueva_lstm_svm_results = load_results("cueva_lstm-svm_results.json")
cueva_lstm_svm_results_sum = summarize_results(estimator_name="lstm-svm", results=cueva_lstm_svm_results)

c:\Users\LARRY\Documents\Scripts\thesis-writing-1\server-side\modelling\utilities\loaders.py:201: RuntimeWarning: Mean of empty slice.
  mean_metric_value = np.array(value).mean()
c:\Users\LARRY\anaconda3\envs\thesis-writing-1\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [7]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [8]:
# svm_hyper_param_config = {'C': 1, 'gamma': 0.001}
# lr_hyper_param_config = {'C': 1}
# rf_hyper_param_config = {'n_estimators': 200}
# gbt_hyper_param_config = {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 3}
# svm = SVC(**svm_hyper_param_config, verbose=1)
# lr = LogisticRegression(**lr_hyper_param_config, verbose=1)
# rf = RandomForestClassifier(**rf_hyper_param_config, verbose=1)
# gbt = GradientBoostingClassifier(**gbt_hyper_param_config, verbose=1)