In [1]:
import os
import pandas as pd
import re
import itertools
import json
import numpy as np

from utilities.loaders import load_results, summarize_results
from argparse import ArgumentParser

In [2]:
# load results.json 
hossain_lr_results = load_results("hossain_lr_results.json")
hossain_lr_results_sum = summarize_results(estimator_name="lr", results=hossain_lr_results)

In [3]:
hossain_lr_results

{'lr': {'C_0.01': {'folds_train_acc': [0.9229457884280219,
    0.9221511455301613,
    0.9218371992831487,
    0.9234847173135879,
    0.9224638677194537,
    0.9235238681435435,
    0.9245776393860388,
    0.9220773580036842,
    0.9219671914442527,
    0.9240545449479046,
    0.9240440501682472,
    0.9226869358380093,
    0.9232613543041222,
    0.9229358686046245,
    0.9276017061287551,
    0.9219193292891015,
    0.9262464985994397,
    0.9315749857596224,
    0.9245905547355661,
    0.9270013077360362,
    0.92603411150685,
    0.9259991742572138,
    0.9232780568361659,
    0.9228947983457134,
    0.9315202919402116,
    0.9258745573354206,
    0.9223818403372247,
    0.9228345617077239,
    0.9234229303546291,
    0.9231309017131176,
    0.9227973898758512,
    0.9220804306442636,
    0.9218086014871992],
   'folds_cross_acc': [0.96050690044267,
    0.9954669084315503,
    0.9917548226509023,
    0.9438483259378782,
    0.9804321239298818,
    0.9382179675994109,
    0.9247620380739082,
    0.9806935742386711,
    0.9948102773523907,
    0.9230472516875603,
    0.9248073480189928,
    0.9734147810375978,
    0.9522761888644441,
    0.9582532051282051,
    0.8086706995501783,
    0.9894939449835592,
    0.8503259032751267,
    0.6632713191346072,
    0.9009525571071858,
    0.8310758212673206,
    0.8556499575191164,
    0.855877048537599,
    0.9473932160804021,
    0.9639467038230427,
    0.7087013175039815,
    0.8713953488372093,
    0.9785643070787637,
    0.9685221412057621,
    0.9436310395314788,
    0.9535947158946566,
    0.9661031205315839,
    0.9927163667523564,
    0.9943172972131403],
   'folds_train_prec': [0.7976865372501861,
    0.7987360510134366,
    0.7988987036824595,
    0.7990953853200504,
    0.8004997444488614,
    0.7986367837338263,
    0.8030801176674165,
    0.7985019154897364,
    0.7989846557526668,
    0.8015584415584416,
    0.7974166024767435,
    0.7989170703904246,
    0.79941071119071,
    0.797424155695478,
    0.7923871049464817,
    0.7977566670481859,
    0.7963381286410652,
    0.8024099883855982,
    0.7988018269173736,
    0.8001326419872181,
    0.8015714642055375,
    0.7978517344602923,
    0.797211293682018,
    0.7978765911296307,
    0.7954051311784317,
    0.7983876087094521,
    0.7975938126611286,
    0.8001367365542388,
    0.7982849907918969,
    0.797953081876725,
    0.7988403467478041,
    0.7985049075553526,
    0.7988919351153758],
   'folds_cross_prec': [0.8958333333333334,
    0.38095238095238093,
    0.96875,
    0.8048780487804879,
    0.23577235772357724,
    0.8333333333333334,
    0.5823714585519413,
    0.6296296296296297,
    0.0,
    0.49206349206349204,
    0.7742782152230971,
    0.47368421052631576,
    0.6741935483870968,
    0.6715328467153284,
    0.9295558958652373,
    0.8108108108108109,
    0.8844765342960289,
    0.9208847299021693,
    0.8506224066390041,
    0.8287769784172662,
    0.7657021877205363,
    0.8629629629629629,
    0.9336734693877551,
    0.7857142857142857,
    0.8255072463768116,
    0.7924528301886793,
    0.8505747126436781,
    0.4177215189873418,
    0.8305084745762712,
    0.8924731182795699,
    0.7875,
    0.85,
    0.574468085106383],
   'folds_train_rec': [0.3420419388105878,
    0.3407247291980376,
    0.33902100625562887,
    0.3446343029285397,
    0.343436312250268,
    0.34321318637672527,
    0.3481881611523745,
    0.3411089399120664,
    0.3401491051263994,
    0.3434910583986742,
    0.33784360487008913,
    0.34261341415721547,
    0.34125829284534,
    0.3426975966150894,
    0.3324740898219506,
    0.33946182880798736,
    0.3440782883415098,
    0.313677639046538,
    0.33828183873398643,
    0.3438795605306799,
    0.3315706657724353,
    0.3468929437284675,
    0.3412417345649967,
    0.3426904312437177,
    0.3140290137056854,
    0.3268875893437297,
    0.3403911980440098,
    0.3431224041045688,
    0.34293413765822783,
    0.3418394994827331,
    0.34130488103998036,
    0.3402966926070039,
    0.3399936799630521],
   'folds_cross_rec': [0.0872210953346856,
    0.17777777777777778,
    0.22794117647058823,
    0.04576976421636616,
    0.1657142857142857,
    0.12834224598930483,
    0.450487012987013,
    0.12186379928315412,
    0.0,
    0.3139240506329114,
    0.4263005780346821,
    0.05863192182410423,
    0.31101190476190477,
    0.1619718309859155,
    0.3382557815547506,
    0.19480519480519481,
    0.21434820647419073,
    0.3621006857334002,
    0.29098651525904895,
    0.21926151503616292,
    0.4424959216965742,
    0.11455260570304818,
    0.21785714285714286,
    0.05116279069767442,
    0.45422647527910687,
    0.5357142857142857,
    0.23197492163009403,
    0.5709342560553633,
    0.12710765239948119,
    0.13365539452495975,
    0.1403118040089087,
    0.1717171717171717,
    0.3375],
   'folds_train_f1': [0.47878465001976317,
    0.4776805475160884,
    0.47603260590939384,
    0.48157477054723624,
    0.4806574258776192,
    0.48010278491561914,
    0.48576512455516013,
    0.47801605367197797,
    0.47715891670924887,
    0.48090175572254734,
    0.4746085484553534,
    0.4795661768479395,
    0.47832549778761063,
    0.4793792260972798,
    0.4684101162507722,
    0.47626368745622577,
    0.4805308940902161,
    0.4510363962787661,
    0.4752863117401048,
    0.48102504621407083,
    0.4690984070215134,
    0.48354736579986485,
    0.4779147807086,
    0.4794539342800302,
    0.45028412004841323,
    0.46385631039315484,
    0.47714848770456686,
    0.4802845319927499,
    0.4797661870503597,
    0.4786342472840145,
    0.4782690886593686,
    0.4772184707727986,
    0.4769894453254216],
   'folds_cross_f1': [0.1589648798521257,
    0.24242424242424243,
    0.36904761904761907,
    0.08661417322834646,
    0.19463087248322147,
    0.22242817423540315,
    0.5080091533180778,
    0.2042042042042042,
    0.0,
    0.38330757341576505,
    0.5498602050326188,
    0.10434782608695652,
    0.4256619144602851,
    0.26099290780141843,
    0.49601634320735444,
    0.31413612565445026,
    0.34507042253521125,
    0.5198079231692677,
    0.4336329984135378,
    0.34677904876580373,
    0.5608684414577411,
    0.20225694444444445,
    0.3532818532818533,
    0.09606986899563319,
    0.5860082304526749,
    0.639269406392694,
    0.3645320197044335,
    0.4824561403508772,
    0.2204724409448819,
    0.23249299719887956,
    0.2381852551984877,
    0.2857142857142857,
    0.4251968503937008],
   'folds_train_roc_auc': [0.6660150183737817,
    0.6653541900113609,
    0.664518874712265,
    0.6673360877395869,
    0.6667255178860444,
    0.6666444992587429,
    0.6692287812476955,
    0.6655268063928977,
    0.6650716280386479,
    0.6668940921127958,
    0.6640714002446318,
    0.6663037574938185,
    0.6657079814445829,
    0.666321752545661,
    0.6616149745957214,
    0.6647052170778239,
    0.6671969740418283,
    0.6530372284973701,
    0.6643567702459678,
    0.6672534597973582,
    0.6612984607240022,
    0.6685708953315559,
    0.6656423438230709,
    0.6663275738143175,
    0.6530536690577792,
    0.6589547741150906,
    0.6651798547241664,
    0.6665916737041567,
    0.6664938151435144,
    0.6659384614673816,
    0.6656817765164494,
    0.6651375186016144,
    0.6649831987765434],
   'folds_cross_roc_auc': [0.5433838519836286,
    0.5882971729125576,
    0.6139312800591935,
    0.5225422403401516,
    0.5789696325180196,
    0.5632221312983298,
    0.710001472179781,
    0.5601882393456004,
    0.4991036366740652,
    0.6436008562141592,
    0.7056478899943978,
    0.5284322564228333,
    0.6509751790093392,
    0.5790970639147174,
    0.6641843120562577,
    0.5971183911500598,
    0.6040185958906799,
    0.6652876310022933,
    0.6416650993989843,
    0.6038082699948404,
    0.7034329790925455,
    0.5555503955840551,
    0.6083821692765876,
    0.525309975824726,
    0.6872139799513245,
    0.7489028301355989,
    0.615432711305787,
    0.7749715544217677,
    0.5626859966414658,
    0.5663807898616933,
    0.5694128950114473,
    0.585728951427681,
    0.667966669277769]},
  'C_0.1': {'folds_train_acc': [0.9232938522278624,
    0.922554599502153,
    0.9221940954085314,
    0.9237113349561533,
    0.9226725924115847,
    0.9239222877457879,
    0.9250074839000202,
    0.9224273826587055,
    0.9223408825720119,
    0.9244167931157649,
    0.9244366268991536,
    0.9229766406440595,
    0.9236223935887559,
    0.9233968424564558,
    0.9279254932654825,
    0.9223650097540353,
    0.9264960529666412,
    0.9318877654813248,
    0.9248745923299705,
    0.9274397689411417,
    0.9264383244736969,
    0.9264247885945552,
    0.9236450377302232,
    0.9233139588054181,
    0.9318065078338823,
    0.926228943953374,
    0.9228346616941115,
    0.923101139684321,
    0.9238404105561396,
    0.9235707493681957,
    0.9232195260885265,
    0.9224667498608489,
    0.9222037264104048],
   'folds_cross_acc': [0.9604201024216648,
    0.9954669084315503,
    0.9916770379589297,
    0.9439290036304961,
    0.9818997146351407,
    0.9384388807069219,
    0.9246920492721165,
    0.9808392831123416,
    0.9949804321932959,
    0.9255544840887174,
    0.9255079006772009,
    0.9733287447302762,
    0.9521915721780335,
    0.9588942307692307,
    0.808282922289437,
    0.9891731494105381,
    0.8504063732196024,
    0.6644498695176362,
    0.9027097012854897,
    0.8306865950490425,
    0.8554800339847068,
    0.8567395906845449,
    0.9476287688442211,
    0.964295044848907,
    0.7092080498045461,
    0.8727131782945736,
    0.9788135593220338,
    0.9685221412057621,
    0.9441190824792581,
    0.9535100347192819,
    0.9663554546219194,
    0.9928020565552699,
    0.9943951424567959],
   'folds_train_prec': [0.7984812422078658,
    0.7994939555805454,
    0.7988681380871534,
    0.7978067944152394,
    0.799966248523373,
    0.7997144488863507,
    0.8048655131060476,
    0.7992531402059523,
    0.8012355474948991,
    0.8021796188519913,
    0.7980932327308885,
    0.7990635753370565,
    0.8000456907875949,
    0.7989932696114473,
    0.7931963413106127,
    0.7987126644458247,
    0.7955612963832785,
    0.8026344047533824,
    0.7990722799600728,
    0.8013209568011425,
    0.8019163442049014,
    0.7991532304837026,
    0.7971477467199087,
    0.7994576883967913,
    0.79455374964357,
    0.7979015738196352,
    0.7989250353606789,
    0.8001353866982569,
    0.7994880546075085,
    0.800524784667161,
    0.799377299745259,
    0.799120730470071,
    0.7993348740206302],
   'folds_cross_prec': [0.8936170212765957,
    0.38095238095238093,
    0.9393939393939394,
    0.8095238095238095,
    0.27184466019417475,
    0.8278145695364238,
    0.58125,
    0.6428571428571429,
    0.0,
    0.5182926829268293,
    0.7733674775928298,
    0.4594594594594595,
    0.6731391585760518,
    0.6896551724137931,
    0.9312741312741313,
    0.7317073170731707,
    0.8846846846846846,
    0.921353065539112,
    0.8466019417475729,
    0.8265895953757225,
    0.7605829285218598,
    0.8371335504885994,
    0.9261083743842364,
    0.8571428571428571,
    0.8243593435070544,
    0.7946524064171123,
    0.8636363636363636,
    0.4181360201511335,
    0.8620689655172413,
    0.8913043478260869,
    0.788235294117647,
    0.8947368421052632,
    0.5833333333333334],
   'folds_train_rec': [0.345970633010853,
    0.3453392917860786,
    0.3435971082929679,
    0.34851103758210283,
    0.3464818243835883,
    0.3476069903683845,
    0.3524645509790682,
    0.34504152418172934,
    0.34330605405667936,
    0.3477454302604566,
    0.34253796912263085,
    0.3462309346890888,
    0.34547562088440575,
    0.3475191262207572,
    0.3364602710603242,
    0.3444782661633995,
    0.3480338016592608,
    0.318161180476731,
    0.34184878171313743,
    0.3489583333333333,
    0.33678128305001676,
    0.3516396580324104,
    0.34607097748829835,
    0.3469562872343034,
    0.3189218575638788,
    0.3320597790773229,
    0.34525672371638144,
    0.34654287808453454,
    0.3474831882911392,
    0.34568205330311835,
    0.34635761589403974,
    0.344795719844358,
    0.3447093998395683],
   'folds_cross_rec': [0.08519269776876268,
    0.17777777777777778,
    0.22794117647058823,
    0.047156726768377254,
    0.16,
    0.13368983957219252,
    0.45292207792207795,
    0.12903225806451613,
    0.0,
    0.3227848101265823,
    0.43641618497109824,
    0.05537459283387622,
    0.30952380952380953,
    0.176056338028169,
    0.33602674839788244,
    0.19480519480519481,
    0.21478565179352582,
    0.3644422144171266,
    0.3094393186657204,
    0.21773886562618958,
    0.4469820554649266,
    0.1263520157325467,
    0.22380952380952382,
    0.05581395348837209,
    0.45661881977671454,
    0.5415451895043731,
    0.23824451410658307,
    0.5743944636678201,
    0.1297016861219196,
    0.1320450885668277,
    0.1492204899777283,
    0.1717171717171717,
    0.35],
   'folds_train_f1': [0.48276570958678816,
    0.4823351820756797,
    0.48052014365223905,
    0.48510886937393666,
    0.4835347919960558,
    0.4845831747240198,
    0.49024313889178756,
    0.4820008871600642,
    0.48066232596093367,
    0.4851695280821327,
    0.479343778542823,
    0.48312556489708214,
    0.4825685544991043,
    0.4843653569224439,
    0.472495894909688,
    0.4813529331700014,
    0.484231215938533,
    0.4556889999796785,
    0.47884449605038615,
    0.48619083721433987,
    0.4743496584798721,
    0.4883832207985539,
    0.4826192819768948,
    0.48390350652237096,
    0.45515241848214466,
    0.4689558977370749,
    0.4821510883482715,
    0.48362514277920793,
    0.4844213138484869,
    0.48285709370537944,
    0.4833062377000086,
    0.48173694403859874,
    0.4816915760869565],
   'folds_cross_f1': [0.15555555555555556,
    0.24242424242424243,
    0.3668639053254438,
    0.0891218872870249,
    0.2014388489208633,
    0.2302025782688766,
    0.5091240875912408,
    0.21492537313432836,
    0.0,
    0.39781591263650545,
    0.5579676674364896,
    0.09883720930232558,
    0.4240570846075433,
    0.2805049088359046,
    0.49385749385749383,
    0.3076923076923077,
    0.34565293910594863,
    0.5222914669223394,
    0.45322245322245325,
    0.34468213317264235,
    0.5630619059851014,
    0.21956428876548484,
    0.3604985618408437,
    0.10480349344978165,
    0.587703992610079,
    0.6441265713047247,
    0.37346437346437344,
    0.4839650145772595,
    0.2254791431792559,
    0.2300140252454418,
    0.250936329588015,
    0.288135593220339,
    0.4375],
   'folds_train_roc_auc': [0.6679467764918241,
    0.6676175523768898,
    0.6667385862660324,
    0.6691779283256222,
    0.6681871628100116,
    0.6688115091224663,
    0.6713627008540752,
    0.6674588579132245,
    0.6666742369297007,
    0.6689803555086347,
    0.6663717665556691,
    0.6680643033930084,
    0.6677755412635498,
    0.6687112102881874,
    0.6635756345812135,
    0.6671693506912654,
    0.6690955825608264,
    0.6552301176232285,
    0.6660979290959116,
    0.6697589180866994,
    0.6638431359551954,
    0.670917354703585,
    0.6679845245724733,
    0.6684477486957251,
    0.655417310459101,
    0.6614560638076409,
    0.6675828041920381,
    0.6682523287408374,
    0.6687399624075557,
    0.6678838368125934,
    0.6681514012037126,
    0.667340202054853,
    0.6672855256256239],
   'folds_cross_roc_auc': [0.5423696532006672,
    0.5882971729125576,
    0.613891971883093,
    0.5232357216161571,
    0.5768982630272953,
    0.5658168454484135,
    0.7110658183728037,
    0.5637724687362812,
    0.49918900460986854,
    0.6490228852303057,
    0.7104876004677527,
    0.5268035919277193,
    0.6502311313902917,
    0.5861393174358441,
    0.6632309991317731,
    0.5969559875771812,
    0.6042373185503472,
    0.6664583953441565,
    0.6505193190521286,
    0.6029980168232719,
    0.7049784713899006,
    0.560843700748072,
    0.6112742978832421,
    0.5277260303947787,
    0.6878799295065969,
    0.7518675140117376,
    0.6186101805832053,
    0.7766560252992746,
    0.5641565794143399,
    0.5655756368826272,
    0.5738235317021508,
    0.5857721629046493,
    0.6742166692777691]},
  'C_1': {'folds_train_acc': [0.9234081797533574,
    0.9225393748239646,
    0.9222654746336079,
    0.9238793884888422,
    0.9227285917192296,
    0.9239580433511175,
    0.9250791246523504,
    0.9225270247137846,
    0.9224425672326265,
    0.9245409201103464,
    0.9245360456816559,
    0.9230630438318289,
    0.9235766280456333,
    0.9234146701744824,
    0.9281039586164346,
    0.9223828369726327,
    0.9266590272472626,
    0.9319767678411588,
    0.9249126330792211,
    0.9275009495744122,
    0.926504422191546,
    0.9264604688384042,
    0.9236654255576708,
    0.9234689211571877,
    0.9320135032569835,
    0.9263666193301328,
    0.9228168541126609,
    0.9232280815779386,
    0.9238276825012155,
    0.9236038015041265,
    0.9232246120669925,
    0.9224921655987821,
    0.9222725546228342],
   'folds_cross_acc': [0.960593698463675,
    0.9959202175883953,
    0.9917548226509023,
    0.9442517144009681,
    0.9819812474520995,
    0.9379970544918999,
    0.9246920492721165,
    0.9809121375491767,
    0.9949804321932959,
    0.9261330761812921,
    0.9255857398614462,
    0.9733287447302762,
    0.9521069554916229,
    0.9590544871794872,
    0.8084380331937335,
    0.9891731494105381,
    0.8504063732196024,
    0.6633555013048237,
    0.905206695644132,
    0.8305309045617313,
    0.8554800339847068,
    0.8569748294518936,
    0.9476287688442211,
    0.964295044848907,
    0.7097871724337629,
    0.871937984496124,
    0.978979727484214,
    0.9686110617108306,
    0.9442004229705547,
    0.9535100347192819,
    0.9663554546219194,
    0.9928020565552699,
    0.9943951424567959],
   'folds_train_prec': [0.7984539863454269,
    0.799797263051191,
    0.799051169095222,
    0.7965542316943559,
    0.7992383939071512,
    0.799157463281339,
    0.8047947155628951,
    0.7987170108603905,
    0.7997864688694089,
    0.802215279750071,
    0.7979615608619686,
    0.799279725395307,
    0.7982032182862342,
    0.798330701556508,
    0.7949086815111334,
    0.798186324208629,
    0.7961187748421791,
    0.8021782460136674,
    0.7966387531984183,
    0.8011390602752729,
    0.801861946469039,
    0.7985894323043127,
    0.7972741788321168,
    0.7991695191066719,
    0.7946056626420956,
    0.7980984340044742,
    0.798237686398554,
    0.8002921184203134,
    0.7981755340245906,
    0.7968820351193157,
    0.7995017269690278,
    0.7988298829882988,
    0.7998085369974096],
   'folds_cross_prec': [0.8979591836734694,
    0.5,
    0.96875,
    0.8260869565217391,
    0.27450980392156865,
    0.8206896551724138,
    0.5804123711340207,
    0.6545454545454545,
    0.0,
    0.524390243902439,
    0.7729591836734694,
    0.4594594594594595,
    0.6709677419354839,
    0.6993006993006993,
    0.9340574088440652,
    0.7317073170731707,
    0.8846846846846846,
    0.9223549488054608,
    0.8490909090909091,
    0.8242074927953891,
    0.7620376831821354,
    0.8343949044585988,
    0.9261083743842364,
    0.8571428571428571,
    0.8229077406455299,
    0.7907348242811502,
    0.8666666666666667,
    0.41919191919191917,
    0.8632478632478633,
    0.8913043478260869,
    0.788235294117647,
    0.8947368421052632,
    0.5833333333333334],
   'folds_train_rec': [0.34746844767470414,
    0.3449264098703065,
    0.3443760192780469,
    0.35162230233591785,
    0.34772439333398303,
    0.3484758216661702,
    0.35343986795708604,
    0.34670249145090376,
    0.34563733942057845,
    0.3493284523485617,
    0.3439437680431781,
    0.34718420023464996,
    0.34621550299652254,
    0.34823251580526926,
    0.33773584905660375,
    0.3450870571045903,
    0.34983176225823853,
    0.31977866061293986,
    0.34410952022105,
    0.34991708126036486,
    0.3377099079113679,
    0.35253285696057163,
    0.34624433492657075,
    0.34916276447081324,
    0.3220120747374746,

In [4]:
hossain_lr_results_sum

                      C_0.01     C_0.1       C_1      C_10     C_100
mean_train_acc      0.924091  0.924456  0.924528  0.924555  0.924529
mean_cross_acc      0.923833  0.924185  0.924284  0.924266  0.924285
mean_train_prec     0.798642  0.799260  0.798850  0.798734  0.798569
mean_cross_prec     0.721565  0.724388  0.730187  0.726007  0.727183
mean_train_rec      0.339257  0.343607  0.344871  0.345291  0.345081
mean_cross_rec      0.237149  0.240835  0.242107  0.242455  0.241823
mean_train_f1       0.476169  0.480554  0.481716  0.482100  0.481869
mean_cross_f1       0.328871  0.333500  0.335708  0.335744  0.335081
mean_train_roc_auc  0.664780  0.666912  0.667513  0.667714  0.667607
mean_cross_roc_auc  0.613177  0.615000  0.615624  0.615760  0.615452

# best hossain lr results come from a hyper param config of C_10

In [5]:
# load results.json 
hossain_gbt_results = load_results("hossain_gbt_results.json")
hossain_gbt_results_sum = summarize_results(estimator_name="gbt", results=hossain_gbt_results)

In [6]:
hossain_gbt_results_sum

,n_estimators_200|learning_rate_0.01|max_depth_3,n_estimators_200|learning_rate_0.01|max_depth_5,n_estimators_200|learning_rate_0.01|max_depth_10,n_estimators_200|learning_rate_0.1|max_depth_3,n_estimators_200|learning_rate_0.1|max_depth_5
mean_train_acc,0.925041,0.929946,0.948694,0.933874,0.939918
mean_cross_acc,0.923915,0.923478,0.922935,0.924987,0.924393
mean_train_prec,0.789136,0.805470,0.924501,0.777757,0.810710
mean_cross_prec,0.762314,0.723141,0.710339,0.684369,0.665413
mean_train_rec,0.361388,0.412491,0.537109,0.485419,0.530289
mean_cross_rec,0.245141,0.265559,0.278777,0.312366,0.321047
mean_train_f1,0.495703,0.545543,0.679426,0.597722,0.641148
mean_cross_f1,0.338489,0.361211,0.372977,0.398501,0.402569
mean_train_roc_auc,0.675208,0.700585,0.766076,0.734892,0.758164
mean_cross_roc_auc,0.616356,0.626510,0.632543,0.648361,0.651873

In [7]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [8]:
# svm_hyper_param_config = {'C': 1, 'gamma': 0.001}
# lr_hyper_param_config = {'C': 1}
# rf_hyper_param_config = {'n_estimators': 200}
# gbt_hyper_param_config = {'n_estimators': 200, 'learning_rate': 0.01, 'max_depth': 3}
# svm = SVC(**svm_hyper_param_config, verbose=1)
# lr = LogisticRegression(**lr_hyper_param_config, verbose=1)
# rf = RandomForestClassifier(**rf_hyper_param_config, verbose=1)
# gbt = GradientBoostingClassifier(**gbt_hyper_param_config, verbose=1)